### ISSUE TITLE
vgg19 can not download

### ISSUE THREAD

**Issue by lp249839965** [mohamedkeid/Style-Transfer-Algorithm#2]
hi, the vgg19 download url https://www.dropbox.com/s/68opci8420g7bcl/vgg19.npy?dl=1 now is 404, could you give a new url.thank you so much

**Comment by alex2wong** [comment]
@lp249839965 , download here: https://pan.baidu.com/s/1o9weflK?errno=0&errmsg=Auth%20Login%20Sucess&&bduss=&ssnerror=0&traceid=   or  https://github.com/machrisaa/tensorflow-vgg

**Comment by mkeid** [comment]
Thanks @alex2wong ! Dropbox removed the file a little while ago I realized. My apologies for the inconvenience @lp249839965 

I will update the repo to reflect this ASAP
